#declaring a try and accept block
try:
    num = int(input("enter a string: "))
    print(num)
except:
    print("an error has occured!")